### ISSUE TITLE
default: You are already using composer version c83650f299cfff1049cd61ea72ee5345bd4f92d3.

### ISSUE THREAD

**Issue by Neabfi** [FriendsOfCake/vagrant-chef#37]
Hello,

I try to use vagrant-chef on mac OS-X but I have an error when I execute vagrant up.
"default: You are already using composer version c83650f299cfff1049cd61ea72ee5345bd4f92d3."
When I go to http://192.168.13.37/ I have "File not found."
Thx ;)

**Comment by rawroland** [comment]
The following line in the Vagrantfile is responsible for the error:
`config.vm.provision :shell, inline: "/usr/local/bin/composer self-update"`
This is because the current version of **composer** is installed during the php installation process:

    remote_file node['php']['composer']['bin'] do
        source node['php']['composer']['url']
        mode "0755"
        action :create
        not_if { ::File.exists?(node['php']['composer']['bin']) }
    end

In the `install.rb` for the php recipe.

I don't get the error upon installation, but still get the __"File not found"__ error though.

**Comment by bilson** [comment]
File not found is fixed in #39

**Comment by rawroland** [comment]
@bilson The pull request seems not to have been merged with the master branch.

**Comment by josegonzalez** [comment]
Fixed by #39
